- name: Hide shutdown button
  hosts: windows
  gather_facts: no
  tasks:
    - name: Set register HideShutDown to 1
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\PolicyManager\default\Start\HideShutDown
        name: value
        data: 1
        type: dword
    - name: Set register HideSleep to 1
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\PolicyManager\default\Start\HideSleep
        name: value
        data: 1
        type: dword        
               
 