- name: Install PollingLoginSshWorkerService
  hosts: windows
  gather_facts: no
  tasks:
    - name: Copy Packages
      win_copy:
        src: /mnt/c/Users/developer/source/repos/wongcyrus/PollingLoginSshServices/IoTSshClientService/bin/Debug/net6.0/win-x64/
        dest: c:\IoTSshClientService\
    - name: Create a new service IoTSshClientService
      win_service:
        name: IoTSshClientService
        path: c:\IoTSshClientService\IoTSshClientService.exe
        display_name: IoTSshClientService
        description: IoT Ssh Client Service
        start_mode: auto
        state: restarted
    - name: Check IoTSshClientService is installed
      win_service:
        name: IoTSshClientService
      register: service_info
    - debug: msg="{{ inventory_hostname }} => {{ service_info.state }}"
               
 