- name: Install Basic Software
  hosts: windows
  tasks:   
    - name: Install tightvnc
      ansible.windows.win_powershell:
        script: |
          Invoke-WebRequest -Uri 'https://www.tightvnc.com/download/2.8.63/tightvnc-2.8.63-gpl-setup-64bit.msi' -OutFile 'd:\tightvnc-2.8.63-gpl-setup-64bit.msi';          
          msiexec.exe /i "d:\tightvnc-2.8.63-gpl-setup-64bit.msi" /quiet /norestart SET_USEVNCAUTHENTICATION=1 VALUE_OF_USEVNCAUTHENTICATION=1 SET_PASSWORD=1 VALUE_OF_PASSWORD=controller SET_VIEWONLYPASSWORD=1 VALUE_OF_VIEWONLYPASSWORD=viewer SET_USECONTROLAUTHENTICATION=1 VALUE_OF_USECONTROLAUTHENTICATION=1 SET_CONTROLPASSWORD=1 VALUE_OF_CONTROLPASSWORD=vncadmin SET_ALLOWLOOPBACK=1 VALUE_OF_ALLOWLOOPBACK=1