- name: Install IoTSshClientService
  hosts: windows
  gather_facts: no
  tasks:
    - name: Copy Packages
      win_copy:
        src: /mnt/c/Users/developer/source/repos/wongcyrus/AzureHybridCloudLabEnvironment/IoTSshClientService/bin/Debug/net6.0/win-x64/publish/win-x64/
        dest: c:\IoTSshClientService\
    - name: Create a new service IoTSshClientService
      win_service:
        name: IoTSshClientService
        path: c:\IoTSshClientService\IoTSshClientService.exe
        display_name: IoTSshClientService
        description: IoT Ssh Client Service
        start_mode: auto
        state: restarted
        failure_actions:
        - type: restart
        - type: restart
          delay_ms: 2000
        - type: restart
          delay_ms: 5000
        - type: restart
    - name: Check IoTSshClientService is installed
      win_service:
        name: IoTSshClientService
      register: service_info
    - debug: msg="{{ inventory_hostname }} => {{ service_info.state }}"
               
 