- name: Reboot all PC
  hosts: windows
  gather_facts: no
  tasks:
  - name: Unconditionally reboot the machine
    win_command: shutdown /r
    register: reboot
  - debug: msg="{{ reboot.stdout }}"      

               
 