- name: Uninstall PollingLoginSshWorkerService
  hosts: windows
  tasks:
    - name: Remove PollingLoginSshWorkerService
      win_service:
        name: PollingLoginSshWorkerService
        state: absent
    - name: Check PollingLoginSshWorkerService is installed
      win_service:
        name: PollingLoginSshWorkerService
      register: service_info
    - name: Remove directory
      ansible.windows.win_file:
        path: /cygdrive/c/PollingLoginSshWorkerService/
        state: absent

               
 